tag_constants_data_sizes = dict()
TAG_CONSTANT_ARRAY = 91
TAG_CONSTANT_BYTE = 66
TAG_CONSTANT_CHAR = 67
TAG_CONSTANT_OBJECT = 76
TAG_CONSTANT_FLOAT = 70
TAG_CONSTANT_DOUBLE = 68
TAG_CONSTANT_INT = 73
TAG_CONSTANT_LONG = 74
TAG_CONSTANT_SHORT = 83
TAG_CONSTANT_VOID = 86
TAG_CONSTANT_BOOLEAN = 90
TAG_CONSTANT_STRING = 115
TAG_CONSTANT_THREAD = 116
TAG_CONSTANT_THREAD_GROUP = 103
TAG_CONSTANT_CLASS_LOADER = 108
TAG_CONSTANT_CLASS_OBJECT = 99
tag_constants_data_sizes[TAG_CONSTANT_ARRAY] = 8
tag_constants_data_sizes[TAG_CONSTANT_BYTE] = 1
tag_constants_data_sizes[TAG_CONSTANT_CHAR] = 2
tag_constants_data_sizes[TAG_CONSTANT_OBJECT] = 8
tag_constants_data_sizes[TAG_CONSTANT_FLOAT] = 4
tag_constants_data_sizes[TAG_CONSTANT_DOUBLE] = 8
tag_constants_data_sizes[TAG_CONSTANT_INT] = 4
tag_constants_data_sizes[TAG_CONSTANT_LONG] = 8
tag_constants_data_sizes[TAG_CONSTANT_SHORT] = 2
tag_constants_data_sizes[TAG_CONSTANT_VOID] = 0
tag_constants_data_sizes[TAG_CONSTANT_BOOLEAN] = 8
tag_constants_data_sizes[TAG_CONSTANT_STRING] = 8
tag_constants_data_sizes[TAG_CONSTANT_THREAD] = 8
tag_constants_data_sizes[TAG_CONSTANT_THREAD_GROUP] = 8
tag_constants_data_sizes[TAG_CONSTANT_CLASS_LOADER] = 8
tag_constants_data_sizes[TAG_CONSTANT_CLASS_OBJECT] = 8

VM_CMDSET											=	1
VM_CMD_VERSION									=	1
VM_CMD_CLASSES_BY_SIGNATURE		 	=	2
VM_CMD_ALL_CLASSES							=	3
VM_CMD_ALL_THREADS							=	4
VM_CMD_TOP_LEVEL_THREAD_GROUPS	=	5
VM_CMD_DISPOSE									=	6
VM_CMD_ID_SIZES								 	=	7
VM_CMD_SUSPEND									=	8
VM_CMD_RESUME									 	=	9
VM_CMD_EXIT										 	= 10
VM_CMD_CREATE_STRING						= 11
VM_CMD_CAPABILITIES						 	= 12
VM_CMD_CLASSPATHS							 	= 13
VM_CMD_DISPOSE_OBJECTS					= 14
VM_CMD_HOLD_EVENTS							= 15
VM_CMD_RELEASE_EVENTS					 	= 16
VM_CMD_CAPABILITIES_NEW				 	= 17
VM_CMD_REDEFINE_CLASSES				 	= 18
VM_CMD_SET_DEFAULT_STRATUM			= 19

REF_TYPE_CMDSET											=	2
REF_TYPE_CMD_SIGNATURE							 =	1
REF_TYPE_CMD_CLASS_LOADER						=	2
REF_TYPE_CMD_MODIFIERS							 =	3
REF_TYPE_CMD_FIELDS									=	4
REF_TYPE_CMD_METHODS								 =	5
REF_TYPE_CMD_GET_VALUES							=	6
REF_TYPE_CMD_SOURCE_FILE						 =	7
REF_TYPE_CMD_NESTED_TYPES						=	8
REF_TYPE_CMD_STATUS									=	9
REF_TYPE_CMD_INTERFACES							=	10
REF_TYPE_CMD_CLASS_OBJECT						=	11
REF_TYPE_CMD_SOURCE_DEBUG_EXTENSION	=	12
REF_TYPE_CMD_SIGNATURE_WITH_GENERIC	=	13
REF_TYPE_CMD_FIELDS_WITH_GENERIC		 =	14
REF_TYPE_CMD_METHODS_WITH_GENERIC		=	15
REF_TYPE_CMD_INSTANCES							 =	16
REF_TYPE_CMD_CLASS_FILE_VERSION			=	17
REF_TYPE_CMD_CONSTANT_POOL	=	18

CLASS_TYPE_CMDSET = 3
CLASS_TYPE_CMD_SUPERCLASS = 1
CLASS_TYPE_CMD_SET_VALUES = 2
CLASS_TYPE_CMD_INVOKE_METHOD = 3
CLASS_TYPE_CMD_NEW_INSTANCE = 4

ARRAY_TYPE_CMDSET = 4
ARRAY_TYPE_CMD_NEW_INSTANCE = 1

METHOD_CMDSET = 6
METHOD_CMD_LINE_TABLE = 1
METHOD_CMD_VARIABLE_TABLE = 2
METHOD_CMD_BYTECODES = 3
METHOD_CMD_IS_OBSOLETE = 4
METHOD_CMD_VARIABLE_TABLE_WITH_GENERIC = 5

OBJ_REF_CMDSET = 9
OBJ_REF_CMD_REFERENCE_TYPE = 1
OBJ_REF_CMD_GET_VALUES = 2
OBJ_REF_CMD_SET_VALUES = 3
OBJ_REF_CMD_MONITOR_INFO = 5
OBJ_REF_CMD_INVOKE_METHOD = 6
OBJ_REF_CMD_DISABLE_COLLECTION = 7
OBJ_REF_CMD_ENABLE_COLLECTION = 8
OBJ_REF_CMD_IS_COLLECTED = 9
OBJ_REF_CMD_REFERRING_OBJECTS = 10

STR_REF_CMDSET = 10
STR_REF_CMD_VALUE = 1

THREAD_REF_CMDSET = 11
THREAD_REF_CMD_NAME = 1
THREAD_REF_CMD_SUSPEND = 2
THREAD_REF_CMD_RESUME = 3
THREAD_REF_CMD_STATUS = 4
THREAD_REF_CMD_THREAD_GROUP = 5
THREAD_REF_CMD_FRAMES = 6
THREAD_REF_CMD_FRAME_COUNT = 7
THREAD_REF_CMD_OWNED_MONITORS = 8
THREAD_REF_CMD_CURRENT_CONTENDED_MONITOR = 9
THREAD_REF_CMD_STOP = 10
THREAD_REF_CMD_INTERRUPT = 11
THREAD_REF_CMD_SUSPEND_COUNT = 12
THREAD_REF_CMD_OWNED_MONITORS_STACK_DEPTH_INFO = 13
THREAD_REF_CMD_FORCE_EARLY_RETURN = 14

THREAD_GRP_REF_CMDSET = 12
THREAD_GRP_REF_CMD_NAME = 1
THREAD_GRP_REF_CMD_PARENT = 2
THREAD_GRP_REF_CMD_CHILDREN = 3

ARRAY_REF_CMDSET = 13
ARRAY_REF_CMD_LENGTH = 1
ARRAY_REF_CMD_GET_VALUES = 2
ARRAY_REF_CMD_SET_VALUES = 3

CLASS_LOADER_REF_CMDSET = 14
CLASS_LOADER_REF_CMD_VISIBLE_CLASSES = 1

EVENT_REQ_CMDSET = 15
EVENT_REQ_CMD_SET = 1
EVENT_REQ_CMD_CLEAR = 2
EVENT_REQ_CMD_CLEAR_ALL_BREAKPOINTS = 3

STACK_FRAME_CMDSET = 16
STACK_FRAME_CMD_GET_VALUES = 1
STACK_FRAME_CMD_SET_VALUES = 2
STACK_FRAME_CMD_THIS_OBJECT = 3
STACK_FRAME_CMD_POP_FRAMES = 4

CLASS_OBJ_REF_CMDSET = 17
CLASS_OBJ_REF_CMD_REFLECTED_TYPE = 1

EVENT_CMDSET = 64
EVENT_CMD_COMPOSITE = 100


EVENT_KIND_SINGLE_STEP =	1		
EVENT_KIND_BREAKPOINT =	2		
EVENT_KIND_FRAME_POP =	3		
EVENT_KIND_EXCEPTION =	4		
EVENT_KIND_USER_DEFINED =	5		
EVENT_KIND_THREAD_START =	6		
EVENT_KIND_THREAD_DEATH =	7		
EVENT_KIND_CLASS_PREPARE =	8		
EVENT_KIND_CLASS_UNLOAD =	9		
EVENT_KIND_CLASS_LOAD =	10		
EVENT_KIND_FIELD_ACCESS =	20		
EVENT_KIND_FIELD_MODIFICATION =	21		
EVENT_KIND_EXCEPTION_CATCH =	30		
EVENT_KIND_METHOD_ENTRY =	40		
EVENT_KIND_METHOD_EXIT =	41		
EVENT_KIND_METHOD_EXIT_WITH_RETURN_VALUE =	42		
EVENT_KIND_MONITOR_CONTENDED_ENTER =	43		
EVENT_KIND_MONITOR_CONTENDED_ENTERED =	44		
EVENT_KIND_MONITOR_WAIT =	45		
EVENT_KIND_MONITOR_WAITED =	46		
EVENT_KIND_VM_START =	90		
EVENT_KIND_VM_DEATH =	99		

SUSPEND_POLICY_NONE = 0
SUSPEND_POLICY_EVENT_THREAD = 1
SUSPEND_POLICY_ALL = 2
